### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by ghost** [welder1976/uwow-spp#1]
CMake Warning (dev) at dep/boost/CMakeLists.txt:22 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Boost_ROOT is set to:

    C:\local\boost_1_64_0

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/macros/FindBoost.cmake:1231 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.64.0

  Boost include path: C:/local/boost_1_64_0

  Could not find the following static Boost libraries:

          boost_system
          boost_filesystem
          boost_thread
          boost_program_options
          boost_iostreams
          boost_regex

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.  If you still have problems search on forum for TCE00020.
Call Stack (most recent call first):
  dep/boost/CMakeLists.txt:22 (find_package)

**Comment by Ramys** [comment]
The errors shows it's an issue with OpenSSLCrypto﻿. So check if you have installed openssl well and if cmake can find it. And if it's the right version: 32 or 64 bit.
Look this..
https://community.trinitycore.org/topic/120-compile-or-cmake-problems/page/117/
I linked manually!!

**Comment by ghost** [comment]
I have no idea how to fix it but I have installed all the dependencies just as it is on the trinity wiki. Could you compile this?

**Comment by welder1976** [comment]
need opensll 1.0

**Comment by ghost** [comment]
using Win64OpenSSL-1_0_2u x64
