### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ghost** [welder1976/uwow-spp#3]
using VS2017 v15.9.13, boost_1_64_0-msvc-14.0-64, Win64OpenSSL-1_0_2u, OS window 10
![Captura](https://user-images.githubusercontent.com/35294381/76138033-917fbe00-6011-11ea-8466-1205bc84c89f.PNG)

**Comment by eragels** [comment]
In your build you use boost 1.66 but you need 1.64, just regenerate your build in cmake

**Comment by ghost** [comment]
install boost 1.64 for msvc14.0 and I get this error now in the build I test with bosst 1.64msvc14.1 and then I get error in cmake
![Captura](https://user-images.githubusercontent.com/35294381/76145037-cdd40e00-6053-11ea-8723-18036043bd58.PNG)

**Comment by Ramys** [comment]
Edit .
System" variable named "BOOST_ROOT" and as value your Boost installation directory, e.g "C:/local/boost_1_64_0". <--- This..

**Comment by ghost** [comment]
exactly that I have done I don't know why I skip this error

**Comment by lowkeywx** [comment]
Boost_LIBRARY_DIR, set this variable value in cmake

**Comment by lowkeywx** [comment]
The source code is old. The Database mismatch.

**Comment by lowkeywx** [comment]
you must use the boost that version number no higher than 1.64
