### ISSUE TITLE
Connection patcher and how to connect server

### ISSUE THREAD

**Issue by bahajan95** [welder1976/uwow-spp#4]
where is the client's connection patcher in the core or how to connect to the client without a connection patcher? just across the realm,? sorry my bad english)

**Comment by bahajan95** [comment]
map extractors not compiled, how can find maps?

**Comment by ghost** [comment]
Here is a repack of this code perhaps with some improvements included with its maps and its DB ( https://www.emucoach.com/legion-7-3-5-/6945-repack-7-3-5-legion-wow-repack-wow-legion-7-3-5-repack-blizzlike-fun.html )

**Comment by bahajan95** [comment]
big th, but i register this site I can 't download it

**Comment by bahajan95** [comment]
please can you put the Repack in another source? I will be grateful

**Comment by ghost** [comment]
Data: https://mega.nz/#!Mv41VRBY!_wn4-kvY457MDzd72dY17NRnqAF7CM2nE5MitVD6e38
DB: https://mega.nz/#!drwV2Q6A!zbUI_w1cnTfVp_FCw_IpS8YtsCIexSe9eJFSV_8zwJ8
Core: https://mega.nz/#!6YsS0QyJ!r7_4wlGQAfcEtbr25cCd-1ql8p3XIeHbUHCD7Wt2lGw

**Comment by bahajan95** [comment]
big th
