### ISSUE TITLE
Install Linux

### ISSUE THREAD

**Issue by warcrafte** [welder1976/uwow-spp#7]
Hi Guys

please give me info for install for unix os

**Comment by eragels** [comment]
You can find more info on TC wiki.
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977288/Linux+Requirements

**Comment by warcrafte** [comment]
@flcore
can u updated this links?

 Data: https://mega.nz/#!Mv41VRBY!_wn4-kvY457MDzd72dY17NRnqAF7CM2nE5MitVD6e38
 DB: https://mega.nz/#!drwV2Q6A!zbUI_w1cnTfVp_FCw_IpS8YtsCIexSe9eJFSV_8zwJ8
 Core: https://mega.nz/#!6YsS0QyJ!r7_4wlGQAfcEtbr25cCd-1ql8p3XIeHbUHCD7Wt2lGw

**Comment by warcrafte** [comment]
error build


/uwow-spp-master/src/common/Logging/Log.h:128:18: fatal error: use of class template 'boost::asio::strand' requires template arguments
    boost::asio::strand* _strand;


/uwow-spp-master/src/server/shared/PrecompiledHeaders/sharedPCH.h:4:
/home/uwow-spp-master/src/common/Logging/Log.h:128:18: fatal error: use of class template 'boost::asio::strand' requires template arguments
    boost::asio::strand* _strand;
